version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "azul/zulu-openjdk-alpine"
        update-types:
          - version-update:semver-major
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
