name: Build

on: push

env:
  JAVA_VERSION: 25
  JAVA_DIST: zulu
  JAVA_ARCH: x64

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          architecture: ${{ env.JAVA_ARCH }}

      - name: Build and test
        run: ./gradlew check jar

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: |
            **/build/reports/tests/test
            **/build/reports/jacoco/test/html