name: Release

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: write

jobs:
  preflight:
    uses: ./.github/workflows/release-001-preflight.yaml

  jar:
    uses: ./.github/workflows/release-002-jar.yaml
    if: ${{ needs.preflight.outputs.cleared == 'true' }}
    needs:
      - preflight

  native:
    uses: ./.github/workflows/release-003-native.yaml
    if: ${{ needs.preflight.outputs.cleared == 'true' }}
    needs:
      - preflight
      - jar

  docker:
    uses: ./.github/workflows/release-004-docker.yaml
    if: ${{ needs.preflight.outputs.cleared == 'true' }}
    needs:
      - preflight
      - jar
      - native
    with:
      version: ${{ needs.preflight.outputs.version }}

  finalize:
    uses: ./.github/workflows/release-005-finalize.yaml
    if: ${{ needs.preflight.outputs.cleared == 'true' }}
    needs:
      - preflight
      - jar
      - native
      - docker
    with:
      version: ${{ needs.preflight.outputs.version }}
