name: Release (Native)
on:
  workflow_call:
    inputs:
      version:
        description: Version
        type: string
        required: true

env:
  JAVA_VERSION: 25
  JAVA_DIST: graalvm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Java
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Create directories
        run: |
          mkdir -p build
          mkdir -p build/libs
          mkdir -p build/bin

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: build/libs/miner-exporter-${{ inputs.version }}.jar

      - name: Build
        run:
          native-image -jar build/libs/miner-exporter-${{ inputs.version }}.jar \
          build/bin/miner-exporter-${{ inputs.version }}-linux-amd64

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: miner-exporter-${{ inputs.version }}-linux-amd64
          path: build/bin/miner-exporter-${{ inputs.version }}-linux-amd64
